version: '3.8'

services:
  postgres:
    container_name: purchase-db_postgres
    image: postgres
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=purchase-db