version: '3.8'

services:
  postgres:
    container_name: notificacao-db_postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notificacao-db