version: '3.8'

services:
  postgres:
    container_name: auth-db_postgres
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth-db