server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: person-service
          uri: http://localhost:8081
          predicates:
            - Path=/person/**
          filters:
            - name: JwtAuthFilter

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**
          filters:
            - name: JwtAuthFilter

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - name: JwtAuthFilter

        - id: purchase-service
          uri: http://localhost:8084
          predicates:
            - Path=/purchases/**
          filters:
            - name: JwtAuthFilter

        - id: stock-service
          uri: http://localhost:8085
          predicates:
            - Path=/stock/**
          filters:
            - name: JwtAuthFilter

  webflux:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
