server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - JwtAuthFilter

        - id: purchase-service
          uri: http://localhost:8084
          predicates:
            - Path=/purchases/**

        - id: stock-service
          uri: http://localhost:8085
          predicates:
            - Path=/stock/**
