server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        #Auth Service (SEM filtro de autenticação)
        - id: auth-service
          uri: http://localhost:8089
          predicates:
            - Path=/auth/**

        #Notification Service
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**
          filters:
            - name: JwtAuthFilter

        #Product Service
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - name: JwtAuthFilter

        #Purchase Service
        - id: purchase-service
          uri: http://localhost:8084
          predicates:
            - Path=/purchases/**
          filters:
            - name: JwtAuthFilter

        #Stock Service
        - id: stock-service
          uri: http://localhost:8085
          predicates:
            - Path=/stock/**
          filters:
            - name: JwtAuthFilter

  webflux:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
