server:
  port: 8080

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:

        # Rota aberta (sem autenticação) para SSE
        - id: notification-subscribe
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/subscribe

        # Protegido por autenticação (restante do notification-service)
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            #- Path=/notifications/unread, /notifications/*/read
            - Path=/notifications/**
          filters:
            - JwtAuth

        - id: auth-service
          uri: http://localhost:8089
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - JwtAuth

        - id: purchase-service
          uri: http://localhost:8084
          predicates:
            - Path=/purchases/**
          filters:
            - JwtAuth

        - id: stock-service
          uri: http://localhost:8085
          predicates:
            - Path=/stock/**
          filters:
            - JwtAuth

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
