server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: person-service
          uri: http://localhost:8081
          predicates:
            - Path=/person/**
          filters:
            - JwtAuthFilter

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**

        - id: purchase-service
          uri: http://localhost:8084
          predicates:
            - Path=/purchases/**

        - id: stock-service
          uri: http://localhost:8085
          predicates:
            - Path=/stock/**

