version: '3.8'

services:
  postgres:
    container_name: stock-db_postgres
    image: postgres
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stock-db