spring:
  profiles:
    active: home
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

notification:
  service:
    url: http://localhost:8088

server:
  port: 8087