server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/person-db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextial-creation: true
    properties:
      hibernate:
        show_sql: true